version: '3.9'

services:

  db-test:
    image: postgres:16
    container_name: pomodoro_db_test
    restart: always
    shm_size: 128mb
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro-test

  cache-test:
    image: redis:7.4.1-alpine
    container_name: pomodoro_cache_test
    restart: always
    ports:
      - '6379:6379'
