"""access_token_delete

Revision ID: e177248db47b
Revises: 41c61cf069ce
Create Date: 2024-10-21 13:53:01.352604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e177248db47b'
down_revision: Union[str, None] = '41c61cf069ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfile', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
